RAW_DATA = {'primary': [{'ts': 1000,
              'severity': 'CRITICAL',
              'source': 'db',
              'msg': 'connection timeout'},
             {'ts': 1001,
              'severity': 'WARNING',
              'source': 'cache',
              'msg': 'eviction spike'},
             {'ts': 1002,
              'severity': 'CRITICAL',
              'source': 'api',
              'msg': 'rate limit hit'},
             {'ts': 1003,
              'severity': 'INFO',
              'source': 'db',
              'msg': 'query completed'},
             {'ts': 1004,
              'severity': 'WARNING',
              'source': 'api',
              'msg': 'slow response'}],
 'alternate_error': [{'ts': 2000,
                      'severity': 'ERROR',
                      'source': 'auth',
                      'msg': 'token expired'},
                     {'ts': 2001,
                      'severity': 'ERROR',
                      'source': 'auth',
                      'msg': 'invalid signature'},
                     {'ts': 2002,
                      'severity': 'CRITICAL',
                      'source': 'auth',
                      'msg': 'key rotation failed'}],
 'trap_catching_input': [{'ts': 3000,
                          'severity': 'INFO',
                          'source': 'scheduler',
                          'msg': 'job started'},
                         {'ts': 3001,
                          'severity': 'INFO',
                          'source': 'scheduler',
                          'msg': 'job completed'},
                         {'ts': 3002,
                          'severity': 'WARNING',
                          'source': 'scheduler',
                          'msg': 'job slow'}]}

RAW_EVENTS = {'primary': [{'ts': 1000,
              'severity': 'CRITICAL',
              'source': 'db',
              'msg': 'connection timeout'},
             {'ts': 1001,
              'severity': 'WARNING',
              'source': 'cache',
              'msg': 'eviction spike'},
             {'ts': 1002,
              'severity': 'CRITICAL',
              'source': 'api',
              'msg': 'rate limit hit'},
             {'ts': 1003,
              'severity': 'INFO',
              'source': 'db',
              'msg': 'query completed'},
             {'ts': 1004,
              'severity': 'WARNING',
              'source': 'api',
              'msg': 'slow response'}],
 'alternate_error': [{'ts': 2000,
                      'severity': 'ERROR',
                      'source': 'auth',
                      'msg': 'token expired'},
                     {'ts': 2001,
                      'severity': 'ERROR',
                      'source': 'auth',
                      'msg': 'invalid signature'},
                     {'ts': 2002,
                      'severity': 'CRITICAL',
                      'source': 'auth',
                      'msg': 'key rotation failed'}],
 'trap_catching_input': [{'ts': 3000,
                          'severity': 'INFO',
                          'source': 'scheduler',
                          'msg': 'job started'},
                         {'ts': 3001,
                          'severity': 'INFO',
                          'source': 'scheduler',
                          'msg': 'job completed'},
                         {'ts': 3002,
                          'severity': 'WARNING',
                          'source': 'scheduler',
                          'msg': 'job slow'}]}

SEVERITY_LEVELS = {'INFO': 0, 'WARNING': 1, 'ERROR': 2, 'CRITICAL': 3}

ALERT_THRESHOLD = 'CRITICAL'
