USER_DB = {'ORG-100:alice': {'user': 'alice',
                   'org': 'ORG-100',
                   'role': 'admin',
                   'tier': 'enterprise'},
 'ORG-200:bob': {'user': 'bob',
                 'org': 'ORG-200',
                 'role': 'viewer',
                 'tier': 'starter'},
 'DEPT-50:carol': {'user': 'carol',
                   'org': 'DEPT-50',
                   'role': 'editor',
                   'tier': 'growth'},
 'GUEST:dan': {'user': 'dan',
               'org': 'GUEST',
               'role': 'guest',
               'tier': 'default'}}

PERMISSIONS = {'enterprise': {'admin', 'read', 'write'},
 'growth': {'read', 'write'},
 'starter': {'read'},
 'default': {'read'}}

RAW_DATA = {'primary': {'org_id': 'ORG-100',
             'user': 'alice',
             'action': 'PURCHASE',
             'required_permission': 'write'},
 'generalization': {'org_id': 'DEPT-50',
                    'user': 'carol',
                    'action': 'PURCHASE',
                    'required_permission': 'write'},
 'trap_catching': {'org_id': 'GUEST',
                   'user': 'dan',
                   'action': 'PURCHASE',
                   'required_permission': 'write'}}
