USER_PROFILES = {'Alice_Smith': {'tier': 'premium', 'region': 'us-east'},
 'Bob_Jones': {'tier': 'standard', 'region': 'eu-west'},
 'Carol-Wu': {'tier': 'premium', 'region': 'ap-south'},
 'dan_lee': {'tier': 'standard', 'region': 'us-west'},
 'SYSADMIN': {'tier': 'admin', 'region': 'global'}}

RAW_EVENTS = {'primary': [{'event_type': 'PURCHASE',
              'user_id': 'Alice_Smith',
              'amount': '99.50',
              'currency': 'USD'},
             {'event_type': 'PURCHASE',
              'user_id': 'Bob_Jones',
              'amount': '45.00',
              'currency': 'EUR'}],
 'hyphen_user': [{'event_type': 'REFUND',
                  'user_id': 'Carol-Wu',
                  'amount': '30.00',
                  'currency': 'USD'}],
 'sysadmin': [{'event_type': 'AUDIT',
               'user_id': 'SYSADMIN',
               'amount': '0',
               'currency': 'USD'}],
 'already_lower': [{'event_type': 'PURCHASE',
                    'user_id': 'dan_lee',
                    'amount': '10.00',
                    'currency': 'USD'}]}
